name: Spark
options:
  bundleIdPrefix: com.konradmichalik
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16"
settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "0.4.1"
    CURRENT_PROJECT_VERSION: "11"
targets:
  Spark:
    type: application
    platform: macOS
    sources:
      - Spark
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.konradmichalik.spark
        INFOPLIST_FILE: Spark/Info.plist
        CODE_SIGN_ENTITLEMENTS: Spark/Spark.entitlements
        PRODUCT_NAME: Spark
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - SparkTests
  SparkTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - SparkTests
    dependencies:
      - target: Spark
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.konradmichalik.spark.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Spark.app/Contents/MacOS/Spark"
