name: Build

on:
  push:

jobs:
  build:
    name: Xcode Build
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Build
        run: xcodebuild -scheme Spark -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Test
        run: xcodebuild -scheme Spark -configuration Debug test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
