name: Lint

on:
  push:

jobs:
  swift:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint
        run: swiftlint lint --strict --reporter github-actions-logging
